/* Glossary: [term, plain meaning, the pond equivalent]. Keys match data-g attributes. */
window.PP_GLOSSARY = {
  agent: ["Agent", "The learner that acts. In robotics, the control policy running on the robot.", "The duckling."],
  env: ["Environment", "Everything the agent acts on: it takes an action and answers with a new situation and a reward.", "The pond: the current, the reeds, the bread boat."],
  reward: ["Reward", "One number after each step saying how good that step was. The only feedback the agent ever gets.", "Breadcrumbs."],
  ret: ["Return (G)", "The total reward from now on, with later rewards discounted by γ. The thing the agent tries to make large.", "All the crumbs from here to the far bank, with far-off ones counting a bit less."],
  gamma: ["Discount (γ)", "A number just under 1. A reward k steps away is worth γᵏ of a reward now. 1/(1−γ) is roughly how many steps ahead the agent cares.", "How much the duckling cares about crumbs that are still far away."],
  episode: ["Episode", "One run from start to finish: a game, a crossing, one attempt at walking until the robot falls or time runs out.", "One crossing of the pond."],
  policy: ["Policy (π)", "The agent's habits: for each situation, how likely it is to do each thing. In deep RL, a neural network.", "The duckling's habits."],
  stochastic: ["Stochastic policy", "A policy that outputs probabilities and samples from them, so the same situation can lead to different actions. That randomness is how it explores.", "Sometimes it tries the other route."],
  gradient: ["Gradient", "The direction to nudge the network's numbers to make something bigger. Policy gradient: the direction that makes good actions more likely.", "Which way to adjust the habit."],
  reinforce: ["REINFORCE", "The simplest policy-gradient algorithm (Unit 4): after an episode, make each action taken more likely in proportion to the return that followed.", "After a crossing, lean toward the route just taken, more so if the haul was big."],
  variance: ["Variance", "How much an estimate jumps around from sample to sample. High variance means you need many samples before the average is trustworthy.", "One lucky crossing can say B is amazing; the next says it's terrible."],
  baseline: ["Baseline", "A number subtracted from the return before the update, usually the critic's V(s). It doesn't change the average gradient; it cuts the noise.", "Mama's guess of the usual haul."],
  critic: ["Critic / value function V(s)", "A second network that predicts the expected return from a situation. Used to score actions, not to choose them.", "Mama Duck, who knows what a crossing from here usually earns."],
  advantage: ["Advantage (A)", "How much better an action turned out than the critic expected: return − V(s), or its estimate. Positive: do it more. Negative: do it less.", "\"Better than Mama expected.\""],
  td: ["TD error (δ)", "δ = r + γ·V(next) − V(here): one step's reward plus the critic's guess from where you landed, minus its guess from where you started. The critic's one-step surprise.", "Mama's surprise after a single paddle."],
  bootstrap: ["Bootstrapping", "Using the critic's own estimate in place of the rest of the real future, so you can learn after one step instead of waiting for the episode to end.", "Mama fills in the rest of the crossing with her guess."],
  onpolicy: ["On-policy", "Learning only from data collected by the current policy. PPO is on-policy: each batch is reused for K epochs, with the ratio correcting for the drift, then thrown away.", "Only this lesson's crossings count."],
  ratio: ["Probability ratio (r)", "r = π_new(a|s) ÷ π_old(a|s): how much more or less likely the updated policy makes an action than the policy that collected the data. 1 means no change.", "How far the habit has drifted since this batch was collected."],
  clip: ["Clip (ε)", "PPO caps the credit for any change that takes the ratio outside [1 − ε, 1 + ε]. ε is usually 0.2.", "The lane ropes."],
  epoch: ["Epoch", "One full pass over a batch of collected data. PPO reuses each batch for several epochs.", "Going over the same batch of crossings again."],
  minibatch: ["Minibatch", "A slice of the batch; each slice gives one gradient step. 4 minibatches × 5 epochs = 20 steps per batch.", "A quarter of the batch at a time."],
  surrogate: ["Surrogate objective", "The quantity PPO actually climbs: ratio × advantage, clipped. Its gradient at r = 1 equals the ordinary policy gradient.", "The score for one lesson, with the lane ropes in place."],
  gae: ["GAE (λ)", "Generalized Advantage Estimation: the advantage as a sum of future TD errors, each faded by γλ per step. λ = 0 is one-step TD; λ = 1 is the full return minus V. Used but never explained in the course; used by every real PPO.", "Adding up Mama's surprises along the boardwalk, fainter the further away."],
  rollout: ["Rollout", "A stretch of experience collected with the current policy before an update. Microduck: 24 steps from each of 4,096 simulated robots.", "A 24-plank walk along the boardwalk."],
  entropy: ["Entropy bonus", "A small bonus in the training objective (not an environment reward) for keeping the policy's choices spread out, so it keeps exploring instead of committing too early.", "A treat for still trying other routes."],
  penalty: ["Penalty term", "A reward term meant to be negative: it charges for something unwanted (jerky moves, joint limits). In the logs it must always read ≤ 0.", "A crumb fine on the scorecard."],
  hacking: ["Reward hacking", "The policy finds a way to score well that isn't the behaviour you wanted. Not a bug in RL; RL does exactly what the reward says.", "Hopping on its bottom next to the crumb dispenser."],
  potential: ["Potential-based shaping", "Pay for progress (the change in a quantity), not for being in a state. Rising pays, holding still pays nothing, so it can't be farmed. (The textbook form, γ·Φ(next) − Φ(now), also guarantees it can't change which policy is best.)", "Crumbs for getting up, none for lying there."],
  curriculum: ["Curriculum", "Changing the task or reward over training: start easy or untaxed, harden once the skill exists.", "No fines for splashing until the duckling can actually swim."],
  dr: ["Domain randomization", "Training in many slightly different simulated worlds (friction, mass, sensor tilt) so the policy survives the real one, which is never exactly the simulator.", "Practising on slippery rocks and grippy sand, not one perfect lane."],
  envs: ["Parallel environments", "Many copies of the simulation running at once on a GPU, all collecting experience for the same policy. Microduck uses 4,096.", "The whole flock practising at once."],
  kl: ["KL divergence", "A measure of how different two probability distributions are. rsl_rl, Microduck's training library, uses it to size each update and adjust the learning rate.", "How much the habit changed in one lesson."],
  smoke: ["Smoke test", "A tiny run (64 environments, 5 iterations) to catch config mistakes before the expensive run.", "Five quick splashes before booking the whole pond."],
  obsnorm: ["Observation normalization", "Rescaling each sensor reading using running averages so they're on similar scales. The same rescaling must ship with the exported model.", "Translating every sense into the same units."]
};
